export default {
  CREATE_CART: "CREATE_CART",
  ADD_ITEM: "ADD_ITEM",
  INCREMENT_ITEM: "INCREMENT_ITEM",
  DECREMENT_ITEM: "DECREMENT_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  EMPTY_CART: "EMPTY_CART"
}