export default {
  SIGNUP_USER: "SIGNUP_USER",
  SIGNIN_USER: "SIGNIN_USER",
  SIGNOUT_USER: "SIGNOUT_USER",
  EDIT_USER_PROFILE: "EDIT_USER_PROFILE",
  ADD_TO_FAVORITES: "ADD_TO_FAVORITES",
  REMOVE_FROM_FAVORITES: "REMOVE_FROM_FAVORITES",
  SUBMIT_ORDER: "SUBMIT_ORDER",  
}